CREATE TABLE marsis_echoes_meta ( 
	orbit_id	bigint,
	echo_id		bigint,
	sub_sc_lon	double precision,
	sub_sc_lat	double precision,
	coordinate	GEOGRAPHY(POINT,4326),
	f1 		real,
	f2		real,
 	slope		real,
	scet_frame_w	bigint,
	scet_frame_f   	integer,
	h_scet		real,
	vt_scet		real,
	vr_scet		real,
	delta_s_scet	real,
	na_scet_1	integer,
	na_scet_2	integer,
	geom_ephem_t 	double precision,
	geom_epoch_utc	varchar(24),
	solar_lon	double precision,
	mars_sun_dist 	double precision,
	target_name	varchar(6),
	target_sc_pos_x	double precision,
	target_sc_pos_y	double precision,
	target_sc_pos_z	double precision,
	sc_alt		double precision,
	target_sc_vel_x	double precision,
	target_sc_vel_y double precision,
	target_sc_vel_z	double precision,
	target_sc_rad_v	double precision,
	target_sc_tan_v	double precision,
	loc_solar_t	double precision,
	solar_zen	double precision,
	di_uni_x	double precision,
	di_uni_y	double precision,
	di_uni_z	double precision,
	mono_uni_x	double precision,
	mono_uni_y	double precision,
	mono_uni_z	double precision,
	CONSTRAINT echo PRIMARY KEY(orbit_id,echo_id)
);

